<?php

add_action("acf/include_fields", function () {
    if (!function_exists("acf_add_local_field_group")) {
        return;
    }

    acf_add_local_field_group([
        "key" => "group_68de75d382bbb",
        "title" => "Диапазон дат",
        "fields" => [
            [
                "key" => "field_68de75d32373b",
                "label" => "Дата от",
                "name" => "apw_date_from",
                "aria-label" => "",
                "type" => "date_picker",
                "instructions" => "",
                "required" => 0,
                "conditional_logic" => 0,
                "wrapper" => [
                    "width" => "",
                    "class" => "",
                    "id" => "",
                ],
                "display_format" => "d/m/Y",
                "return_format" => "d/m/Y",
                "first_day" => 1,
                "default_to_current_date" => 0,
                "allow_in_bindings" => 0,
            ],
            [
                "key" => "field_68de76482373d",
                "label" => "По текущую дату?",
                "name" => "apw_id_date_to",
                "aria-label" => "",
                "type" => "true_false",
                "instructions" => "",
                "required" => 0,
                "conditional_logic" => 0,
                "wrapper" => [
                    "width" => "",
                    "class" => "",
                    "id" => "",
                ],
                "message" => "",
                "default_value" => 0,
                "allow_in_bindings" => 0,
                "ui_on_text" => "По Н/А",
                "ui_off_text" => "Выкл.",
                "ui" => 1,
            ],
            [
                "key" => "field_68de761e2373c",
                "label" => "Дата до",
                "name" => "apw_date_to",
                "aria-label" => "",
                "type" => "date_picker",
                "instructions" => "",
                "required" => 0,
                "conditional_logic" => [
                    [
                        [
                            "field" => "field_68de76482373d",
                            "operator" => "!=",
                            "value" => "1",
                        ],
                    ],
                ],
                "wrapper" => [
                    "width" => "",
                    "class" => "",
                    "id" => "",
                ],
                "display_format" => "d/m/Y",
                "return_format" => "d/m/Y",
                "first_day" => 1,
                "default_to_current_date" => 0,
                "allow_in_bindings" => 0,
            ],
        ],
        "location" => [
            [
                [
                    "param" => "post_type",
                    "operator" => "==",
                    "value" => "apw_experience",
                ],
            ],
        ],
        "menu_order" => 0,
        "position" => "side",
        "style" => "default",
        "label_placement" => "top",
        "instruction_placement" => "label",
        "hide_on_screen" => "",
        "active" => true,
        "description" => "Задаёт дату от и до (или по н/а).",
        "show_in_rest" => 0,
    ]);

    acf_add_local_field_group([
        "key" => "group_68de687253b37",
        "title" => "Обо мне",
        "fields" => [
            [
                "key" => "field_68de6d2d0a868",
                "label" => "Фотография",
                "name" => "apw_profile_photo",
                "aria-label" => "",
                "type" => "group",
                "instructions" => "",
                "required" => 0,
                "conditional_logic" => 0,
                "wrapper" => [
                    "width" => "",
                    "class" => "",
                    "id" => "",
                ],
                "layout" => "block",
                "sub_fields" => [
                    [
                        "key" => "field_68de6cf00a867",
                        "label" => "Настольное",
                        "name" => "apw_profile_photo_desktop",
                        "aria-label" => "",
                        "type" => "image",
                        "instructions" => "",
                        "required" => 1,
                        "conditional_logic" => 0,
                        "wrapper" => [
                            "width" => "",
                            "class" => "",
                            "id" => "",
                        ],
                        "return_format" => "url",
                        "library" => "uploadedTo",
                        "min_width" => 380,
                        "min_height" => 476,
                        "min_size" => "",
                        "max_width" => "",
                        "max_height" => "",
                        "max_size" => 1,
                        "mime_types" => "jpg, jpeg, png, webp",
                        "allow_in_bindings" => 0,
                        "preview_size" => "medium",
                    ],
                    [
                        "key" => "field_68de6e240a869",
                        "label" => "Планшетное",
                        "name" => "apw_profile_photo_tablet",
                        "aria-label" => "",
                        "type" => "image",
                        "instructions" => "",
                        "required" => 1,
                        "conditional_logic" => 0,
                        "wrapper" => [
                            "width" => "",
                            "class" => "",
                            "id" => "",
                        ],
                        "return_format" => "url",
                        "library" => "uploadedTo",
                        "min_width" => 282,
                        "min_height" => 472,
                        "min_size" => "",
                        "max_width" => "",
                        "max_height" => "",
                        "max_size" => 1,
                        "mime_types" => "jpg, jpeg, png, webp",
                        "allow_in_bindings" => 0,
                        "preview_size" => "medium",
                    ],
                    [
                        "key" => "field_68de6e670a86a",
                        "label" => "Мобильное",
                        "name" => "apw_profile_photo_mobile",
                        "aria-label" => "",
                        "type" => "image",
                        "instructions" => "",
                        "required" => 1,
                        "conditional_logic" => 0,
                        "wrapper" => [
                            "width" => "",
                            "class" => "",
                            "id" => "",
                        ],
                        "return_format" => "url",
                        "library" => "uploadedTo",
                        "min_width" => 282,
                        "min_height" => 282,
                        "min_size" => "",
                        "max_width" => "",
                        "max_height" => "",
                        "max_size" => 1,
                        "mime_types" => "jpg, jpeg, png, webp",
                        "allow_in_bindings" => 0,
                        "preview_size" => "medium",
                    ],
                ],
            ],
            [
                "key" => "field_68de6bd60a865",
                "label" => "Биография",
                "name" => "apw_bio",
                "aria-label" => "",
                "type" => "group",
                "instructions" => "",
                "required" => 0,
                "conditional_logic" => 0,
                "wrapper" => [
                    "width" => "",
                    "class" => "",
                    "id" => "",
                ],
                "layout" => "block",
                "sub_fields" => [
                    [
                        "key" => "field_68de687249868",
                        "label" => "ФИО",
                        "name" => "apw_fio",
                        "aria-label" => "",
                        "type" => "text",
                        "instructions" => "",
                        "required" => 1,
                        "conditional_logic" => 0,
                        "wrapper" => [
                            "width" => "",
                            "class" => "",
                            "id" => "",
                        ],
                        "default_value" => "Анпилогов Артём",
                        "maxlength" => 255,
                        "allow_in_bindings" => 0,
                        "placeholder" => "Пупкин Залупкин",
                        "prepend" => "",
                        "append" => "",
                    ],
                    [
                        "key" => "field_68de68e449869",
                        "label" => "Специальность",
                        "name" => "apw_job_title",
                        "aria-label" => "",
                        "type" => "text",
                        "instructions" => "",
                        "required" => 1,
                        "conditional_logic" => 0,
                        "wrapper" => [
                            "width" => "",
                            "class" => "",
                            "id" => "",
                        ],
                        "default_value" => "Frontend разработчик",
                        "maxlength" => 255,
                        "allow_in_bindings" => 0,
                        "placeholder" => "Инженер",
                        "prepend" => "",
                        "append" => "",
                    ],
                    [
                        "key" => "field_68de6c5e0a866",
                        "label" => "Обо мне",
                        "name" => "apw_about_me_text",
                        "aria-label" => "",
                        "type" => "textarea",
                        "instructions" => "",
                        "required" => 1,
                        "conditional_logic" => 0,
                        "wrapper" => [
                            "width" => "",
                            "class" => "",
                            "id" => "",
                        ],
                        "default_value" => "",
                        "maxlength" => 260,
                        "allow_in_bindings" => 0,
                        "rows" => 8,
                        "placeholder" => "",
                        "new_lines" => "",
                    ],
                    [
                        "key" => "field_68de7ac3444cb",
                        "label" => "Почта",
                        "name" => "apw_email",
                        "aria-label" => "",
                        "type" => "email",
                        "instructions" => "",
                        "required" => 0,
                        "conditional_logic" => 0,
                        "wrapper" => [
                            "width" => "",
                            "class" => "",
                            "id" => "",
                        ],
                        "default_value" => "",
                        "allow_in_bindings" => 0,
                        "placeholder" => "",
                        "prepend" => "",
                        "append" => "",
                    ],
                ],
            ],
            [
                "key" => "field_68de6ed5dd009",
                "label" => "Мои технологии",
                "name" => "apw_my_techs",
                "aria-label" => "",
                "type" => "group",
                "instructions" => "",
                "required" => 0,
                "conditional_logic" => 0,
                "wrapper" => [
                    "width" => "",
                    "class" => "",
                    "id" => "",
                ],
                "layout" => "block",
                "sub_fields" => [
                    [
                        "key" => "field_68de6fbddd00c",
                        "label" => "Изображения технологий",
                        "name" => "apw_img_teches",
                        "aria-label" => "",
                        "type" => "gallery",
                        "instructions" => "",
                        "required" => 0,
                        "conditional_logic" => 0,
                        "wrapper" => [
                            "width" => "",
                            "class" => "",
                            "id" => "",
                        ],
                        "return_format" => "array",
                        "library" => "uploadedTo",
                        "min" => "",
                        "max" => "",
                        "min_width" => "",
                        "min_height" => "",
                        "min_size" => "",
                        "max_width" => "",
                        "max_height" => "",
                        "max_size" => "",
                        "mime_types" => "",
                        "insert" => "append",
                        "preview_size" => "medium",
                    ],
                ],
            ],
            [
                "key" => "field_68de706db68b4",
                "label" => "Линкер",
                "name" => "apw_linker",
                "aria-label" => "",
                "type" => "group",
                "instructions" => "",
                "required" => 0,
                "conditional_logic" => 0,
                "wrapper" => [
                    "width" => "",
                    "class" => "",
                    "id" => "",
                ],
                "layout" => "block",
                "sub_fields" => [
                    [
                        "key" => "field_68de70c1b68b5",
                        "label" => "Повторитель ссылок",
                        "name" => "apw_linker_repeater",
                        "aria-label" => "",
                        "type" => "repeater",
                        "instructions" => "",
                        "required" => 0,
                        "conditional_logic" => 0,
                        "wrapper" => [
                            "width" => "",
                            "class" => "",
                            "id" => "",
                        ],
                        "layout" => "block",
                        "pagination" => 0,
                        "min" => 0,
                        "max" => 0,
                        "collapsed" => "",
                        "button_label" => "Добавить",
                        "rows_per_page" => 20,
                        "sub_fields" => [
                            [
                                "key" => "field_68de710bb68b6",
                                "label" => "Ссылка",
                                "name" => "apw_link",
                                "aria-label" => "",
                                "type" => "link",
                                "instructions" => "",
                                "required" => 1,
                                "conditional_logic" => 0,
                                "wrapper" => [
                                    "width" => "",
                                    "class" => "",
                                    "id" => "",
                                ],
                                "return_format" => "url",
                                "allow_in_bindings" => 0,
                                "parent_repeater" => "field_68de70c1b68b5",
                            ],
                            [
                                "key" => "field_68de718eb68b7",
                                "label" => "Текст ссылки",
                                "name" => "apw_link_text",
                                "aria-label" => "",
                                "type" => "text",
                                "instructions" => "",
                                "required" => 1,
                                "conditional_logic" => 0,
                                "wrapper" => [
                                    "width" => "",
                                    "class" => "",
                                    "id" => "",
                                ],
                                "default_value" => "",
                                "maxlength" => 255,
                                "allow_in_bindings" => 0,
                                "placeholder" => "",
                                "prepend" => "",
                                "append" => "",
                                "parent_repeater" => "field_68de70c1b68b5",
                            ],
                            [
                                "key" => "field_68de71b8b68b8",
                                "label" => "Иконка",
                                "name" => "apw_link_icon",
                                "aria-label" => "",
                                "type" => "image",
                                "instructions" => "",
                                "required" => 0,
                                "conditional_logic" => 0,
                                "wrapper" => [
                                    "width" => "",
                                    "class" => "",
                                    "id" => "",
                                ],
                                "return_format" => "url",
                                "library" => "uploadedTo",
                                "min_width" => 24,
                                "min_height" => 24,
                                "min_size" => "",
                                "max_width" => "",
                                "max_height" => "",
                                "max_size" => 1,
                                "mime_types" => "",
                                "allow_in_bindings" => 0,
                                "preview_size" => "thumbnail",
                                "parent_repeater" => "field_68de70c1b68b5",
                            ],
                        ],
                    ],
                ],
            ],
        ],
        "location" => [
            [
                [
                    "param" => "options_page",
                    "operator" => "==",
                    "value" => "apw_about_me",
                ],
            ],
        ],
        "menu_order" => 0,
        "position" => "acf_after_title",
        "style" => "seamless",
        "label_placement" => "top",
        "instruction_placement" => "label",
        "hide_on_screen" => "",
        "active" => true,
        "description" => "Базовые данные обо мне, как о человеке.",
        "show_in_rest" => 0,
    ]);

    acf_add_local_field_group([
        "key" => "group_68de7938b564a",
        "title" => "Ревьюер",
        "fields" => [
            [
                "key" => "field_68de793899574",
                "label" => "ФИО",
                "name" => "apw_review_user_fio",
                "aria-label" => "",
                "type" => "text",
                "instructions" => "",
                "required" => 1,
                "conditional_logic" => 0,
                "wrapper" => [
                    "width" => "",
                    "class" => "",
                    "id" => "",
                ],
                "default_value" => "",
                "maxlength" => 255,
                "allow_in_bindings" => 0,
                "placeholder" => "",
                "prepend" => "",
                "append" => "",
            ],
            [
                "key" => "field_68de797499575",
                "label" => "Должность",
                "name" => "apw_review_user_post",
                "aria-label" => "",
                "type" => "text",
                "instructions" => "",
                "required" => 1,
                "conditional_logic" => 0,
                "wrapper" => [
                    "width" => "",
                    "class" => "",
                    "id" => "",
                ],
                "default_value" => "",
                "maxlength" => 255,
                "allow_in_bindings" => 0,
                "placeholder" => "",
                "prepend" => "",
                "append" => "",
            ],
            [
                "key" => "field_68de799499576",
                "label" => "Фото",
                "name" => "apw_review_user_photo",
                "aria-label" => "",
                "type" => "image",
                "instructions" => "",
                "required" => 0,
                "conditional_logic" => 0,
                "wrapper" => [
                    "width" => "",
                    "class" => "",
                    "id" => "",
                ],
                "return_format" => "url",
                "library" => "uploadedTo",
                "min_width" => 512,
                "min_height" => 512,
                "min_size" => "",
                "max_width" => "",
                "max_height" => "",
                "max_size" => 1,
                "mime_types" => "jpg, jpeg, png, webp",
                "allow_in_bindings" => 0,
                "preview_size" => "thumbnail",
            ],
        ],
        "location" => [
            [
                [
                    "param" => "post_type",
                    "operator" => "==",
                    "value" => "apw_reviews",
                ],
            ],
        ],
        "menu_order" => 0,
        "position" => "normal",
        "style" => "default",
        "label_placement" => "top",
        "instruction_placement" => "label",
        "hide_on_screen" => "",
        "active" => true,
        "description" => "",
        "show_in_rest" => 0,
    ]);

    acf_add_local_field_group([
        "key" => "group_68de781ea3a4c",
        "title" => "Ссылки",
        "fields" => [
            [
                "key" => "field_68de781e9fd9e",
                "label" => "Повторитель ссылок",
                "name" => "apw_links_repeater",
                "aria-label" => "",
                "type" => "repeater",
                "instructions" => "",
                "required" => 0,
                "conditional_logic" => 0,
                "wrapper" => [
                    "width" => "",
                    "class" => "",
                    "id" => "",
                ],
                "layout" => "row",
                "pagination" => 0,
                "min" => 0,
                "max" => 0,
                "collapsed" => "",
                "button_label" => "Добавить",
                "rows_per_page" => 20,
                "sub_fields" => [
                    [
                        "key" => "field_68de78a59fd9f",
                        "label" => "Ссылка",
                        "name" => "apw_link",
                        "aria-label" => "",
                        "type" => "link",
                        "instructions" => "",
                        "required" => 0,
                        "conditional_logic" => 0,
                        "wrapper" => [
                            "width" => "",
                            "class" => "",
                            "id" => "",
                        ],
                        "return_format" => "array",
                        "allow_in_bindings" => 0,
                        "parent_repeater" => "field_68de781e9fd9e",
                    ],
                ],
            ],
        ],
        "location" => [
            [
                [
                    "param" => "post_type",
                    "operator" => "==",
                    "value" => "apw_experience",
                ],
            ],
        ],
        "menu_order" => 0,
        "position" => "normal",
        "style" => "default",
        "label_placement" => "top",
        "instruction_placement" => "label",
        "hide_on_screen" => "",
        "active" => true,
        "description" => "",
        "show_in_rest" => 0,
    ]);
});

add_action( 'init', function() {
	register_post_type( 'apw_experience', array(
		'labels' => array(
			'name' => 'Опыт',
			'singular_name' => 'Опыт',
			'menu_name' => 'Опыт',
			'all_items' => 'Все записи об опыте',
			'edit_item' => 'Изменить опыт',
			'view_item' => 'Просмотреть опыт',
			'view_items' => 'Просмотреть все записи об опыте',
			'add_new_item' => 'Добавить новый опыт',
			'add_new' => 'Добавить опыт',
			'new_item' => 'Новый опыт',
			'parent_item_colon' => 'Родительский опыт:',
			'search_items' => 'Поиск по опыту',
			'not_found' => 'Опыт не найден',
			'not_found_in_trash' => 'В корзине опыт не найден',
			'archives' => 'Архив опыта',
			'attributes' => 'Атрибуты опыта',
			'insert_into_item' => 'Вставить в опыт',
			'uploaded_to_this_item' => 'Загружено в опыт',
			'filter_items_list' => 'Фильтровать список опыта',
			'filter_by_date' => 'Фильтр опыта по дате',
			'items_list_navigation' => 'Навигация по списку опыта',
			'items_list' => 'Список опыта',
			'item_published' => 'Опыт опубликован.',
			'item_published_privately' => 'Опыт опубликован приватно.',
			'item_reverted_to_draft' => 'Опыт преобразован в черновик.',
			'item_scheduled' => 'Опыт запланирован.',
			'item_updated' => 'Опыт обновлён.',
			'item_link' => 'Ссылка на опыт',
			'item_link_description' => 'Ссылка на запись об опыте.',
		),
		'description' => 'Описание моего профессионального опыта.',
		'public' => true,
		'exclude_from_search' => true,
		'publicly_queryable' => false,
		'show_in_menu' => 'apw_career',
		'show_in_rest' => false,
		'menu_icon' => 'dashicons-admin-post',
		'supports' => array( 'title', 'editor', 'excerpt', 'custom-fields' ),
		'rewrite' => false,
		'delete_with_user' => false,
	) );

	register_post_type( 'apw_reviews', array(
		'labels' => array(
			'name' => 'Отзывы',
			'singular_name' => 'Отзыв',
			'menu_name' => 'Отзывы',
			'all_items' => 'Все отзывы',
			'edit_item' => 'Изменить отзыв',
			'view_item' => 'Просмотреть отзыв',
			'view_items' => 'Просмотреть отзывы',
			'add_new_item' => 'Добавить новый отзыв',
			'add_new' => 'Добавить отзыв',
			'new_item' => 'Новый отзыв',
			'parent_item_colon' => 'Родительский отзыв:',
			'search_items' => 'Поиск отзывов',
			'not_found' => 'Отзывы не найдены',
			'not_found_in_trash' => 'В корзине отзывы не найдены',
			'archives' => 'Архив отзывов',
			'attributes' => 'Атрибуты отзыва',
			'insert_into_item' => 'Вставить в отзыв',
			'uploaded_to_this_item' => 'Загружено в отзыв',
			'filter_items_list' => 'Фильтровать список отзывов',
			'filter_by_date' => 'Фильтр отзывов по дате',
			'items_list_navigation' => 'Навигация по списку отзывов',
			'items_list' => 'Список отзывов',
			'item_published' => 'Отзыв опубликован.',
			'item_published_privately' => 'Отзыв опубликован приватно.',
			'item_reverted_to_draft' => 'Отзыв преобразован в черновик.',
			'item_scheduled' => 'Отзыв запланирован.',
			'item_updated' => 'Отзыв обновлён.',
			'item_link' => 'Ссылка на отзыв',
			'item_link_description' => 'Ссылка на отзыв.',
		),
		'description' => 'Отзывы руководителей и коллег обо мне.',
		'public' => true,
		'exclude_from_search' => true,
		'publicly_queryable' => false,
		'show_in_menu' => 'apw_career',
		'show_in_rest' => false,
		'menu_icon' => 'dashicons-admin-post',
		'supports' => array( 'title', 'editor', 'excerpt', 'custom-fields' ),
		'rewrite' => false,
		'delete_with_user' => false,
	) );

	register_post_type( 'apw_coop', array(
		'labels' => array(
			'name' => 'Сотрудничества',
			'singular_name' => 'Сотрудничество',
			'menu_name' => 'Сотрудничества',
			'all_items' => 'Все сотрудничества',
			'edit_item' => 'Изменить сотрудничество',
			'view_item' => 'Просмотреть сотрудничество',
			'view_items' => 'Просмотреть сотрудничества',
			'add_new_item' => 'Добавить новое сотрудничество',
			'add_new' => 'Добавить сотрудничество',
			'new_item' => 'Новое сотрудничество',
			'parent_item_colon' => 'Родительское сотрудничество:',
			'search_items' => 'Поиск сотрудничеств',
			'not_found' => 'Сотрудничества не найдены',
			'not_found_in_trash' => 'В корзине сотрудничества не найдены',
			'archives' => 'Архив сотрудничеств',
			'attributes' => 'Атрибуты сотрудничества',
			'insert_into_item' => 'Вставить в сотрудничество',
			'uploaded_to_this_item' => 'Загружено в сотрудничество',
			'filter_items_list' => 'Фильтровать список сотрудничеств',
			'filter_by_date' => 'Фильтр сотрудничеств по дате',
			'items_list_navigation' => 'Навигация по списку сотрудничеств',
			'items_list' => 'Список сотрудничеств',
			'item_published' => 'Сотрудничество опубликовано.',
			'item_published_privately' => 'Сотрудничество опубликовано приватно.',
			'item_reverted_to_draft' => 'Сотрудничество преобразовано в черновик.',
			'item_scheduled' => 'Сотрудничество запланировано.',
			'item_updated' => 'Сотрудничество обновлено.',
			'item_link' => 'Ссылка на сотрудничество',
			'item_link_description' => 'Ссылка на сотрудничество.',
		),
		'description' => 'Варианты профессионального сотрудничества со мной.',
		'public' => true,
		'exclude_from_search' => true,
		'publicly_queryable' => false,
		'show_in_menu' => 'apw_career',
		'show_in_rest' => false,
		'menu_icon' => 'dashicons-admin-post',
		'supports' => array( 'title', 'editor', 'excerpt', 'thumbnail', 'custom-fields' ),
		'rewrite' => false,
		'delete_with_user' => false,
	) );
});


add_action("acf/init", function () {
    acf_add_options_page([
        "page_title" => "Карьера",
        "menu_slug" => "apw_career",
        "menu_title" => "Карьера",
        "position" => 6,
        "redirect" => true,
        "description" => "Раздел с кастомными типами записей.",
        "menu_icon" => [
            "type" => "dashicons",
            "value" => "dashicons-analytics",
        ],
        "icon_url" => "dashicons-analytics",
    ]);

    acf_add_options_page([
        "page_title" => "Обо мне",
        "menu_slug" => "apw_about_me",
        "menu_title" => "Обо мне",
        "position" => 6,
        "redirect" => false,
        "description" => "Страница обо мне, как о человеке.",
        "menu_icon" => [
            "type" => "dashicons",
            "value" => "dashicons-id-alt",
        ],
        "icon_url" => "dashicons-id-alt",
    ]);
});
