export const CONFIG = {
  email: "contact@anpilogov.pw",
  links: [
    {
      rel: "preload",
      as: "font",
      href: "/fonts/Inter/Inter-VariableFont_opsz,wght.woff2",
      type: "font/woff2",
      crossorigin: "anonymous",
    },
    {
      rel: "preload",
      as: "font",
      href: "/fonts/Inter/Inter-Italic-VariableFont_opsz,wght.woff2",
      type: "font/woff2",
      crossorigin: "anonymous",
    },
    {
      rel: "preload",
      as: "font",
      href: "/fonts/Montserrat/Montserrat-VariableFont_wght.woff2",
      type: "font/woff2",
      crossorigin: "anonymous",
    },
    {
      rel: "preload",
      as: "font",
      href: "/fonts/Montserrat/Montserrat-Italic-VariableFont_wght.woff2",
      type: "font/woff2",
      crossorigin: "anonymous",
    },
    {
      rel: "preload",
      as: "font",
      href: "/fonts/Roboto/Roboto-VariableFont_wdth,wght.woff2",
      type: "font/woff2",
      crossorigin: "anonymous",
    },
    {
      rel: "preload",
      as: "font",
      href: "/fonts/Roboto/Roboto-Italic-VariableFont_wdth,wght.woff2",
      type: "font/woff2",
      crossorigin: "anonymous",
    },
    {
      rel: "preload",
      as: "font",
      href: "/fonts/Roboto_Mono/RobotoMono-VariableFont_wght.woff2",
      type: "font/woff2",
      crossorigin: "anonymous",
    },
    {
      rel: "preload",
      as: "font",
      href: "/fonts/Roboto_Mono/RobotoMono-Italic-VariableFont_wght.woff2",
      type: "font/woff2",
      crossorigin: "anonymous",
    },
  ],
} as const;
